# Guided Capstone Step 4. Pre-Processing and Training Data Development

**The Data Science Method**  


1.   Problem Identification 


2.   Data Wrangling 
  
 
3.   Exploratory Data Analysis   

4.   **Pre-processing and Training Data Development**  
 * Create dummy or indicator features for categorical variables
  * Standardize the magnitude of numeric features
  * Split into testing and training datasets
  * Apply scaler to the testing set
5.   Modeling 
  * Fit Models with Training Data Set
  * Review Model Outcomes — Iterate over additional models as needed.
  * Identify the Final Model

6.   Documentation
  * Review the Results
  * Present and share your findings - storytelling
  * Finalize Code 
  * Finalize Documentation

**<font color='teal'> Start by loading the necessary packages as we did in step 3 and printing out our current working directory just to confirm we are in the correct project directory. </font>**

In [0]:
import os
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [22]:
print('C:\\Users\\arna_mora\\Downloads\\Compressed ')

C:\Users\arna_mora\Downloads\Compressed

In [28]:
import os
path = os.getcwd() 
dir_list = os.listdir(path)   
print("Files and directories in '", path, "' :")  
print(dir_list) 
path = "D:\\Nastaran\\Springboard\\__MACOSX"
os.chdir(path)

Files and directories in ' D:\Nastaran\Springboard\__MACOSX ' :
['._GuidedCapstoneStep3HL.ipynb', '1588204778_GuidedCapstoneStep4_and_step5HL.ipynb.zip', '1589505302_05152020_updated_ski_data_-_updated_ski_data (3).csv', 'GuidedCapstoneStep4 and step5HL.ipynb', '__MACOSX']

**<font color='teal'>  Load the csv file you created in step 3, remember it should be saved inside your data subfolder and print the first five rows.</font>**

In [124]:
import pandas as pd
file =  '1589505302_05152020_updated_ski_data_-_updated_ski_data (3).csv'
df = pd.read_csv(file)
df.head()

,Name,Region,state,summit_elev,vertical_drop,base_elev,trams,fastEight,fastSixes,fastQuads,...,LongestRun_mi,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac
0,Alyeska Resort,Alaska,Alaska,3939,2500,250,1,0.0,0,2,...,1.0,1610.0,113.0,150.0,60.0,669.0,65.0,85.0,150.0,550.0
1,Eaglecrest Ski Area,Alaska,Alaska,2600,1540,1200,0,0.0,0,0,...,2.0,640.0,60.0,45.0,44.0,350.0,47.0,53.0,90.0,NaN
2,Hilltop Ski Area,Alaska,Alaska,2090,294,1796,0,0.0,0,0,...,1.0,30.0,30.0,150.0,36.0,69.0,30.0,34.0,152.0,30.0
3,Arizona Snowbowl,Arizona,Arizona,11500,2300,9200,0,0.0,1,0,...,2.0,777.0,104.0,122.0,81.0,260.0,89.0,89.0,122.0,NaN
4,Sunrise Park Resort,Arizona,Arizona,11100,1800,9200,0,NaN,0,1,...,1.2,800.0,80.0,115.0,49.0,250.0,74.0,78.0,104.0,80.0

## Create dummy features for categorical variables

**<font color='teal'> Create dummy variables for `state`. Add the dummies back to the dataframe and remove the original column for `state`. </font>**

Hint: you can see an example of how to execute this in Aiden's article on preprocessing [here](https://medium.com/@aiden.dataminer/the-data-science-method-dsm-pre-processing-and-training-data-development-fd2d75182967).

In [133]:
df = pd.read_csv(file)
df = pd.concat([df, pd.get_dummies(df['state'])], axis=1).drop(['state'], axis=1)
df = pd.concat([df, pd.get_dummies(df['Region'])], axis=1).drop(['Region'], axis=1)
df

,Name,summit_elev,vertical_drop,base_elev,trams,fastEight,fastSixes,fastQuads,quad,triple,...,Sierra Nevada,South Dakota,Tennessee,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,Alyeska Resort,3939,2500,250,1,0.0,0,2,2,0,...,0,0,0,0,0,0,0,0,0,0
1,Eaglecrest Ski Area,2600,1540,1200,0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Hilltop Ski Area,2090,294,1796,0,0.0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,Arizona Snowbowl,11500,2300,9200,0,0.0,1,0,2,2,...,0,0,0,0,0,0,0,0,0,0
4,Sunrise Park Resort,11100,1800,9200,0,NaN,0,1,2,3,...,0,0,0,0,0,0,0,0,0,0
5,Yosemite Ski & Snowboard Area,7800,600,7200,0,0.0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,Bear Mountain,8805,1665,7140,0,0.0,0,2,1,2,...,1,0,0,0,0,0,0,0,0,0
7,Bear Valley,8500,1900,6600,0,0.0,1,1,0,2,...,1,0,0,0,0,0,0,0,0,0
8,Boreal Mountain Resort,7700,500,7200,0,0.0,0,1,1,3,...,1,0,0,0,0,0,0,0,0,0
9,Dodge Ridge,8200,1600,6600,0,0.0,0,0,1,2,...,1,0,0,0,0,0,0,0,0,0
10,Donner Ski Ranch,8012,750,7031,0,0.0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
11,Heavenly Mountain Resort,10067,3500,7170,2,0.0,2,7,1,5,...,1,0,0,0,0,0,0,0,0,0
12,June Mountain,10090,2590,7545,0,NaN,0,2,0,0,...,1,0,0,0,0,0,0,0,0,0
13,Kirkwood,9800,2000,7800,0,0.0,0,2,1,5,...,1,0,0,0,0,0,0,0,0,0
14,Mammoth Mountain Ski Area,11053,3100,7953,3,0.0,2,9,1,6,...,1,0,0,0,0,0,0,0,0,0
15,Mt. Shasta Ski Park,6890,1435,5500,0,NaN,0,0,0,3,...,1,0,0,0,0,0,0,0,0,0
16,Mountain High,8200,1600,6600,0,NaN,0,2,2,2,...,1,0,0,0,0,0,0,0,0,0
17,Mt. Baldy,8600,2100,6500,0,NaN,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
18,Northstar California,8610,2280,6330,2,0.0,1,7,1,2,...,1,0,0,0,0,0,0,0,0,0
19,Sierra-at-Tahoe,8852,2212,6640,0,NaN,0,3,0,1,...,1,0,0,0,0,0,0,0,0,0
20,Ski China Peak,8709,1679,7030,0,0.0,0,0,1,4,...,1,0,0,0,0,0,0,0,0,0
21,Snow Summit,8200,1200,7000,0,0.0,0,2,0,4,...,1,0,0,0,0,0,0,0,0,0
22,Snow Valley,7841,1041,6800,0,NaN,0,0,0,5,...,1,0,0,0,0,0,0,0,0,0
23,Soda Springs,7352,652,6700,0,NaN,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
24,Sugar Bowl Resort,8383,1500,6883,1,0.0,0,5,3,1,...,1,0,0,0,0,0,0,0,0,0
25,Tahoe Donner,7350,600,6750,0,0.0,0,0,1,1,...,1,0,0,0,0,0,0,0,0,0
26,Arapahoe Basin Ski Area,13050,2530,10780,0,0.0,0,1,2,1,...,0,0,0,0,0,0,0,0,0,0
27,Aspen / Snowmass,12510,4406,8104,3,0.0,1,15,4,3,...,0,0,0,0,0,0,0,0,0,0
28,Beaver Creek,11440,3340,8100,2,0.0,0,11,0,1,...,0,0,0,0,0,0,0,0,0,0
29,Breckenridge,12998,3398,9600,1,0.0,5,6,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,The Summit at Snoqualmie,3865,1025,2840,0,NaN,0,3,3,4,...,0,0,0,0,0,0,1,0,0,0
301,White Pass,6550,2050,4500,0,NaN,0,2,1,1,...,0,0,0,0,0,0,1,0,0,0
302,Canaan Valley Resort,4280,850,3430,0,NaN,0,0,1,2,...,0,0,0,0,0,0,0,1,0,0
303,Snowshoe Mountain Resort,4848,1500,3348,0,NaN,0,3,2,6,...,0,0,0,0,0,0,0,1,0,0
304,Timberline Four Seasons,4265,1000,3268,0,NaN,0,0,0,2,...,0,0,0,0,0,0,0,1,0,0
305,Winterplace Ski Resort,3600,603,2997,0,NaN,0,0,2,3,...,0,0,0,0,0,0,0,1,0,0
306,Alpine Valley Resort,1040,388,820,0,NaN,0,3,0,3,...,0,0,0,0,0,0,0,0,1,0
307,Bruce Mound,1375,375,1000,0,0.0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
308,Cascade Mountain,1280,460,820,0,NaN,0,2,2,3,...,0,0,0,0,0,0,0,0,1,0
309,Christie Mountain,1650,350,1300,0,NaN,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
310,Christmas Mountain,1250,250,1000,0,NaN,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
311,Devils Head,995,500,495,0,NaN,0,0,3,1,...,0,0,0,0,0,0,0,0,1,0
312,Grand Geneva,1086,211,875,0,NaN,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
313,Granite Peak Ski Area,1942,700,1242,0,NaN,1,2,0,2,...,0,0,0,0,0,0,0,0,1,0
314,Little Switzerland,1269,200,1069,0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
315,Mount La Crosse,1110,516,594,0,NaN,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
316,Nordic Mountain,1137,265,872,0,NaN,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
317,Sunburst,1100,214,866,0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
318,Trollhaugen,1200,260,920,0,0.0,0,0,2,0,...,0,0,0,0,0,0,0,0,1,0
319,Tyrol Basin,1160,300,860,0,0.0,0,0,0,3,...,0,0,0,0,0,0,0,0,1,0
320,Whitecap Mountain,1750,400,1295,0,NaN,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
321,Wilmot Mountain,1030,230,800,0,NaN,0,0,3,2,...,0,0,0,0,0,0,0,0,1,0
322,Grand Targhee Resort,9920,2270,7851,0,0.0,0,2,2,0,...,0,0,0,0,0,0,0,0,0,1
323,Hogadon Basin,8000,640,7400,0,NaN,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
324,Jackson Hole,10450,4139,6311,3,0.0,0,4,4,1,...,0,0,0,0,0,0,0,0,0,1
325,Meadowlark Ski Lodge,9500,1000,8500,0,NaN,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
326,Sleeping Giant Ski Resort,7428,810,6619,0,0.0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
327,Snow King Resort,7808,1571,6237,0,NaN,0,0,1,1,...,0,0,0,0,0,0,0,0,0,1
328,Snowy Range Ski & Recreation Area,9663,990,8798,0,0.0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
329,White Pine Ski Area,9500,1100,8400,0,NaN,0,0,0,2,...,0,0,0,0,0,0,0,0,0,1

## Standardize the magnitude of numeric features

**<font color='teal'> Using sklearn preprocessing standardize the scale of the features of the dataframe except the name of the resort which we done't need in the dataframe for modeling, so it can be droppped here as well. Also, we want to hold out our response variable(s) so we can have their true values available for model performance review. Let's set `AdultWeekend` to the y variable as our response for scaling and modeling. Later we will go back and consider the `AdultWeekday`, `dayOpenLastYear`, and `projectedDaysOpen`. For now leave them in the development dataframe. </font>**

In [139]:
from sklearn import preprocessing
x=df.drop(['Name','AdultWeekend'],axis=1)
y=df.AdultWeekend
scaler = preprocessing.StandardScaler().fit(x)
x_scaled=scaler.transform(x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  """

## Split into training and testing datasets

**<font color='teal'> Using sklearn model selection import train_test_split, and create a 75/25 split with the y = `AdultWeekend`. We will start by using the adult weekend ticket price as our response variable for modeling.</font>**

In [136]:
#Import the train_test_split function from the sklearn.model_selection utility. 
import numpy as np
from sklearn.model_selection import train_test_split

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train, y_test= train_test_split(X_scaled, y, test_size=0.25, random_state=1)
(X_train)

array([ 39.  ,  79.  ,  35.  ,  52.  ,  79.99,    nan,  84.  ,    nan,
        40.  ,  52.  ,  60.  ,  59.  ,  79.  ,  78.  ,    nan,  44.  ,
        49.  ,  49.  ,  69.  ,  65.  ,  43.  ,  55.  ,  92.  ,  50.  ,
          nan,  45.  ,  48.  ,  79.  ,  47.  ,  47.  ,  68.  ,  89.  ,
        71.  ,    nan,    nan,  70.  ,  39.  ,  35.  ,  35.34,  79.  ,
        60.  ,  98.  ,  25.  ,  43.  ,  44.  ,  34.  ,  47.  ,  38.  ,
          nan,  57.  , 139.  ,  45.  ,    nan,  59.  ,  68.  ,  68.  ,
        32.  ,  92.  ,  65.  ,    nan,  47.  ,  65.  ,    nan,  91.  ,
       115.  ,    nan,    nan,  42.  ,  89.  ,  92.  ,  65.  ,  44.  ,
        99.  ,    nan,    nan,  47.  ,    nan,  59.  ,  37.  ,    nan,
          nan,  76.  ,  93.  ,  41.  ,  48.  , 119.  ,  77.  ,  84.  ,
        72.  ,  45.  ,    nan,  56.  ,    nan,    nan,  58.  ,  45.  ,
        64.  ,  55.  , 125.  ,  50.  ,  48.  ,  56.  ,  45.  ,  42.  ,
        63.  , 119.  ,  96.  ,  58.  ,  47.  ,  62.  ,  87.  ,  65.  ,
        70.  ,  68.  ,  80.  ,  65.  ,  85.  ,  69.  ,  48.  ,  70.  ,
        49.  ,  44.  ,  45.  ,  46.  ,    nan,    nan,  70.  ,  49.  ,
        60.01,  58.  ,  38.  ,  44.  ,    nan, 110.  ,  80.  ,  48.  ,
        73.  ,  58.  ,  69.  ,  95.  , 105.  ,  70.  ,  81.  ,  71.  ,
        75.  ,    nan,    nan,  67.  ,  75.  ,  63.  ,  99.  ,    nan,
        59.  ,  99.  ,  60.  ,  50.  ,  75.  ,    nan,  35.  ,  55.  ,
        68.  ,  32.  ,  75.  ,    nan,  25.  ,  37.  ,  79.  ,  59.  ,
        83.  ,    nan,  85.  ,  43.  ,  54.  ,  49.  ,    nan,  47.  ,
        62.  ,  34.  ,  42.  ,    nan,  65.  ,  72.  ,  81.  ,  68.  ,
        63.2 ,  30.  ,    nan,  49.  ,  65.  ,  49.  ,    nan,  60.  ,
        93.  ,  79.  , 135.  ,  47.  ,  89.  ,  60.  ,  65.  ,  64.  ,
        20.  ,  81.  ,  52.  ,  69.  ,  60.  ,  71.  ,  59.  ,  59.  ,
        85.  ,  55.  ,  65.  ,    nan,  89.  ,  60.  ,  66.  , 158.  ,
        50.  ,  57.  ,  64.  ,  64.  , 169.  ,  49.  ,  53.  ,  79.  ,
          nan,  42.  ,  45.  ,  65.  ,  39.  ,  40.  ,  55.  ,  89.  ,
          nan,  45.  ,  89.  ,  55.  ,    nan,  60.  ,  39.  ,  17.  ,
        48.  ,  46.  ,  67.  ,  71.  ,  40.  ,    nan,  89.  ])

Here we start the actual modeling work. First let's fit a multiple linear regression model to predict the `AdultWeekend` price.

# Guided Capstone Step 5. Modeling

This is the fifth step in the Data Science Method. In the previous steps you cleaned and prepared the datasets. Now it's time to get into the most exciting part: modeling! In this exercise, you'll build three different models and compare each model's performance. In the end, you'll choose the best model for demonstrating insights to Big Mountain management.



### **The Data Science Method**  


1.   Problem Identification 

2.   Data Wrangling 
  
3.   Exploratory Data Analysis 
 
4.   Pre-processing and Training Data Development

5.   **Modeling**
  * Fit Models with Training Data Set
  * Review Model Outcomes — Iterate over additional models as needed.
  * Identify the Final Model

6.   Documentation
  * Review the Results
  * Present and share your findings - storytelling
  * Finalize Code 
  * Finalize Documentation

## Fit Models with a Training Dataset

**<font color='teal'> Using sklearn, fit the model on your training dataset.</font>**

#### Model 1

In [137]:
#all first model set
#from sklearn import linear_model
#from sklearn.metrics import explained_variance_score,mean_absolute_error
#lm = linear_model.LinearRegression()
#model = lm.fit(X_train,y_train)

**<font color='teal'> Predict on the testing dataset and score the model performance with the y_test set and the y-pred values. The explained variance is a measure of the variation explained by the model. This is also known as the R-squared value. </font>**

Hint: you will have to use the `predict()` method here as it's used in this [DSM article](https://medium.com/@aiden.dataminer/the-data-science-method-dsm-modeling-56b4233cad1b) about modeling.

In [0]:
# Make a variable called y_pred and assign it the result of calling predict() on our model variable with parameter X_test

## Review Model Outcomes — Iterate over additional models as needed

In [0]:
# You might want to use the explained_variance_score() and mean_absolute_error() metrics.
# To do so, you will need to import them from sklearn.metrics. 
# You can plug y_test and y_pred into the functions to evaluate the model

**<font color='teal'> Print the intercept value from the linear model. </font>**

Hint: our linear regression model `lm` has an attribute `intercept_` for the intercept

**<font color='teal'> The intercept is the mean `AdultWeekend` price for all the resorts given the other characteristics. The addition or subtraction of each of the coefficient values in the regression are numeric adjustments applied to the intercept to provide a particular observation's value for the resulting `AdultWeekend` value. Also, because we took the time to scale our x values in the training data, we can compare each of the coeeficients for the features to determine the feature importances. Print the coefficient values from the linear model and sort in descending order to identify the top ten most important features.</font>** 


Hint: make sure to review the absolute value of the coefficients, because the adjustment may be positive or negative, but what we are looking for is the magnitude of impact on our response variable.

In [0]:
# You might want to make a pandas DataFrame displaying the coefficients for each state like so: 
# pd.DataFrame(abs(lm.coef_), X.columns, columns=['Coefficient'])

**<font color='teal'>You should see that the top ten important features are different states. However, the state is not something the managers at the Big Mountain Resort can do anything about. Given that we care more about actionable traits associated with ticket pricing, rebuild the model without the state features and compare the results. </font>**

Hint: Try to construct another model using exactly the steps we followed above.

#### Model 2

**<font color='teal'> When reviewing our new model coefficients, we see `summit_elev` is now in the number two spot. This is also difficult to change from a management prespective and highly correlated with `base_elev` and `vertical_drop`.  This time, rebuild the model without the state features and without the `summit_elev` and without `base_elev`and compare the results. </font>**

#### Model 3

## Identify the Final Model

**<font color='teal'> Review the model performances in the table below and choose the best model for proving insights to Big Mountain management about what features are driving ski resort lift ticket prices. Type your choice in the final markdown cell — you will discuss this selection more in the next step of the guided casptone. </font>**

| Model | Explained Variance| Mean Absolute Error|Features Dropped|
| --- | --- | --- | --- |
| Model 1. | 0. |  |-|
| Model 2. | 0.| |'state'|
| Model 3. | 0. | |'state','summit_elev','base_elev'|

Model Selection: